spring.application.name=jappo-backend

# =========================
# DATABASE
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/jappo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}

# =========================
# MAIL
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# GOOGLE
# =========================
app.google.client-id=${GOOGLE_CLIENT_ID}

# =========================
# IA
# =========================
ai.orchestrator.url=${AI_ORCHESTRATOR_URL}
ai.orchestrator.api-key=${AI_API_KEY}
ai.orchestrator.timeout=${AI_TIMEOUT}

# =========================
# LIVEKIT
# =========================
livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
livekit.host=${LIVEKIT_HOST}


# =========================================================
# PAYDUNYA
# =========================================================

paydunya.master-key=${PAYDUNYA_MASTER_KEY}
paydunya.private-key=${PAYDUNYA_PRIVATE_KEY}
paydunya.token=${PAYDUNYA_TOKEN}

# Sandbox PayDunya
paydunya.base-url=https://app.paydunya.com/sandbox-api/v1

paydunya.callback-url=https://recoil-reverb-carless.ngrok-free.dev/api/paiements/paydunya/ipn

paydunya.return-url=https://jappo-frontend.vercel.app/paiement/succes

paydunya.cancel-url=https://jappo-frontend.vercel.app/paiement/annule

# =========================
# ABONNEMENT
# =========================
app.abonnement.premium.prix=${PREMIUM_PRICE}
app.abonnement.premium.duree-jours=${PREMIUM_DURATION_DAYS}





jappo.super-admin.email=admin@jappo.sn
jappo.super-admin.password=12345678
jappo.super-admin.prenom=Admin
jappo.super-admin.nom=JAPPO